// LOGIN
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// CACHE
export const CACHE_LOGIN = 'CACHE_LOGIN';
export const CACHE_LOGIN_SUCCESS = 'CACHE_LOGIN_SUCCESS';
export const CACHE_LOGIN_FAILED = 'CACHE_LOGIN_FAILED';

export const CACHE_LOGOUT = 'CACHE_LOGOUT';
